server.port: 8088

spring:
  datasource:
    url: jdbc:p6spy:oracle:thin:@//10.10.200.58:1521/TKLDB
    username: TK_ITSMDEV
    password: itsmdev
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        ddl-auto: none

logging.level:
  root: info
  #org.hibernate.SQL: debug
  #org.hibernate.type: trace
  #org.hibernate.type.descriptor.sql.BasicBinder: trace

# decorator:
#   datasource:
#     p6spy:
#       enable-logging: true
